
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class Peso extends javax.swing.JFrame {

    /**
     * Creates new form Peso
     */
    public Peso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEstatura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rbMujer = new javax.swing.JRadioButton();
        rbBato = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        etPesoIdeal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        etPesoIdeal1 = new javax.swing.JLabel();
        etPesoIdeal2 = new javax.swing.JLabel();
        etSobre = new javax.swing.JTextField();
        etBajo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Rangos = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        rbGuardar = new javax.swing.JButton();
        rbSalir = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();
        btCalcular = new javax.swing.JButton();
        rbGuard = new javax.swing.JButton();
        rbMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre del paciente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 60, 117, 34);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(150, 70, 130, 30);

        jLabel2.setText("Estatura en cm");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 110, 90, 30);
        getContentPane().add(txtEstatura);
        txtEstatura.setBounds(150, 110, 130, 30);

        jLabel3.setText("Peso actual");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 150, 90, 30);
        getContentPane().add(txtPeso);
        txtPeso.setBounds(150, 150, 130, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Genero"));
        jPanel1.setLayout(null);

        buttonGroup1.add(rbMujer);
        rbMujer.setText("Mujer");
        rbMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMujerActionPerformed(evt);
            }
        });
        jPanel1.add(rbMujer);
        rbMujer.setBounds(160, 120, 57, 24);

        buttonGroup1.add(rbBato);
        rbBato.setText("Hombre");
        rbBato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBatoActionPerformed(evt);
            }
        });
        jPanel1.add(rbBato);
        rbBato.setBounds(10, 120, 100, 30);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(210, 260, 80, 60);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/males_male_avatar_man_people_faces_18338.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 20, 120, 100);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/females_female_avatar_woman_people_faces_18384.png"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(130, 20, 120, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(320, 40, 280, 160);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));
        jPanel2.setLayout(null);

        jLabel4.setText("Peso Ideal");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 30, 90, 30);

        etPesoIdeal.setBackground(new java.awt.Color(255, 255, 255));
        etPesoIdeal.setOpaque(true);
        jPanel2.add(etPesoIdeal);
        etPesoIdeal.setBounds(100, 30, 90, 30);

        jLabel5.setText("Kg");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(190, 40, 41, 16);

        jLabel7.setText("Sobre Peso");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 80, 70, 30);

        jLabel8.setText("Bajo peso");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 120, 60, 30);

        etPesoIdeal1.setBackground(new java.awt.Color(255, 255, 255));
        etPesoIdeal1.setOpaque(true);
        jPanel2.add(etPesoIdeal1);
        etPesoIdeal1.setBounds(100, 30, 70, 30);

        etPesoIdeal2.setBackground(new java.awt.Color(255, 255, 255));
        etPesoIdeal2.setOpaque(true);
        jPanel2.add(etPesoIdeal2);
        etPesoIdeal2.setBounds(100, 30, 70, 30);

        etSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etSobreActionPerformed(evt);
            }
        });
        jPanel2.add(etSobre);
        etSobre.setBounds(100, 80, 90, 30);
        jPanel2.add(etBajo);
        etBajo.setBounds(100, 120, 90, 30);

        jLabel9.setText("Kg");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(190, 90, 15, 16);

        jLabel10.setText("Kg");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(190, 130, 48, 16);

        jLabel11.setText("Rango de Peso");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(320, 30, 90, 16);

        Rangos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RangosActionPerformed(evt);
            }
        });
        jPanel2.add(Rangos);
        Rangos.setBounds(290, 50, 210, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(50, 290, 530, 160);

        jPanel3.setLayout(null);

        rbGuardar.setText("Guardar");
        rbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(rbGuardar);
        rbGuardar.setBounds(510, 250, 80, 26);

        rbSalir.setText("Salir");
        rbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSalirActionPerformed(evt);
            }
        });
        jPanel3.add(rbSalir);
        rbSalir.setBounds(220, 10, 70, 26);

        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(btLimpiar);
        btLimpiar.setBounds(130, 10, 77, 26);

        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });
        jPanel3.add(btCalcular);
        btCalcular.setBounds(20, 10, 81, 26);

        rbGuard.setText("Guardar");
        rbGuard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGuardActionPerformed(evt);
            }
        });
        jPanel3.add(rbGuard);
        rbGuard.setBounds(310, 10, 80, 26);

        rbMostrar.setText("Mostrar");
        rbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMostrarActionPerformed(evt);
            }
        });
        jPanel3.add(rbMostrar);
        rbMostrar.setBounds(410, 10, 79, 26);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(40, 220, 550, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void rbBatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBatoActionPerformed

    }//GEN-LAST:event_rbBatoActionPerformed

    private void etSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etSobreActionPerformed

    private void RangosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RangosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RangosActionPerformed

    private void rbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbGuardarActionPerformed

    private void rbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_rbSalirActionPerformed
  Archivo objeto=new Archivo(0.0,"Luis",0.0,0.0,0.0,0.0);
    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        txtNombre.setText("");
        txtEstatura.setText("");
        txtPeso.setText("");
        etBajo.setText("");
        etPesoIdeal.setText("");
        etSobre.setText("");
        Rangos.setText("");
    }//GEN-LAST:event_btLimpiarActionPerformed
static String nombre="";
    static double peso2=0,ib1=0,ib2=0,est=0,peso1=0,pesoc=0,pesob=0,peso=0;
    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        nombre=txtNombre.getText();
        est=Double.valueOf(txtEstatura.getText());
        peso=Double.valueOf(txtPeso.getText());
        objeto.setPeso(peso);
        objeto.setNombre(nombre);
        objeto.setEstatura(est);
        if (rbBato.isSelected()) {
            ib1=est-100;
            ib2=(est-100)*0.1;
            peso1=ib1+ib2;
            peso2=ib1-ib2;
            pesoc=peso-peso1;
            pesob=peso2-peso;
            etPesoIdeal.setText(Double.toString(peso1));
            Rangos.setText(Double.toString(peso1)+"Kg a "+Double.toString(peso2)+"Kg");
            objeto.setPesoIdeal(peso1);
            if (pesoc<0) {
                etSobre.setText("0");
                objeto.setSobrePeso(0.0);
            }
            else{
                etSobre.setText(Double.toString(pesoc));
                objeto.setSobrePeso(pesoc);
            }
            if (pesob<0) {
                etBajo.setText("0");
                objeto.setBajoPeso(0.0);
            }
            else{
                etBajo.setText(Double.toString(pesob));
                objeto.setBajoPeso(pesob);
            }
        }
        else{
            if (rbMujer.isSelected()) {
                ib1=est-100;
                ib2=(est-100)*0.15;
                peso1=ib1+ib2;
                peso2=ib1-ib2;
                 objeto.setPesoIdeal(peso1);
                pesoc=peso-peso1;
                pesob=peso2-peso;
                etPesoIdeal.setText(Double.toString(peso1));
                etBajo.setText(Double.toString(pesoc));
                Rangos.setText(Double.toString(peso1)+"Kg a "+Double.toString(peso2)+"Kg");
                if (pesoc<0) {
                    etSobre.setText("0");
                    objeto.setSobrePeso(0.0);
                }
                else{
                    etSobre.setText(Double.toString(pesoc));
                    objeto.setSobrePeso(pesoc);
                }
                if (pesob<0) {
                    etBajo.setText("0");
                    objeto.setBajoPeso(0.0);
                }
                else{
                    etBajo.setText(Double.toString(pesob));
                    objeto.setBajoPeso(pesob);
                }

            }
        }
    }//GEN-LAST:event_btCalcularActionPerformed

    private void rbGuardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGuardActionPerformed

       objeto.almacenarRAM();
        try {
            objeto.almacenDisco();
        } catch (IOException ex) {
            Logger.getLogger(Peso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rbGuardActionPerformed

    private void rbMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMujerActionPerformed
       
    }//GEN-LAST:event_rbMujerActionPerformed

    private void rbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMostrarActionPerformed
        
        try {
            objeto.MostrarDisco();
        } catch (IOException ex) {
            Logger.getLogger(Peso.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_rbMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Peso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Peso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Peso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Peso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Peso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Rangos;
    private javax.swing.JButton btCalcular;
    private javax.swing.JButton btLimpiar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField etBajo;
    private javax.swing.JLabel etPesoIdeal;
    private javax.swing.JLabel etPesoIdeal1;
    private javax.swing.JLabel etPesoIdeal2;
    private javax.swing.JTextField etSobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rbBato;
    private javax.swing.JButton rbGuard;
    private javax.swing.JButton rbGuardar;
    private javax.swing.JButton rbMostrar;
    private javax.swing.JRadioButton rbMujer;
    private javax.swing.JButton rbSalir;
    private javax.swing.JTextField txtEstatura;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
