
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.Scanner;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author luisf
 */
public class ControlAlmacen extends javax.swing.JFrame {

    /**
     * Creates new form ControlAlmacen
     */
    public ControlAlmacen() {
        initComponents();
       this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButAdd = new javax.swing.JButton();
        jButRegresa = new javax.swing.JButton();
        icono = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtID = new javax.swing.JTextField();
        jtprev = new javax.swing.JTextField();
        jtdesc = new javax.swing.JTextField();
        jtstock = new javax.swing.JTextField();
        jtstockm = new javax.swing.JTextField();
        jtipo = new javax.swing.JTextField();
        jtcost = new javax.swing.JTextField();
        jbutInfo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar Producto");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButAdd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inventario.png"))); // NOI18N
        jButAdd.setText("Agregar");
        jButAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAddActionPerformed(evt);
            }
        });
        jPanel1.add(jButAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 140, 50));

        jButRegresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion.png"))); // NOI18N
        jButRegresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegresaActionPerformed(evt);
            }
        });
        jPanel1.add(jButRegresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 50, 30));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/shop-icon_34368.png"))); // NOI18N
        jPanel1.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 30, 20));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Precio venta:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 100, 20));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Descripcion:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 100, 20));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Stock:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 50, 20));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" Stock minimo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 110, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Tipo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 40, 20));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" Costo: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 60, 20));

        jtID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtID.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(jtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 80, -1));

        jtprev.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtprev.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(jtprev, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 80, -1));

        jtdesc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtdesc.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(jtdesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 280, -1));

        jtstock.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtstock.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(jtstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 90, -1));

        jtstockm.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtstockm.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(jtstockm, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 80, -1));

        jtipo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtipo.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(jtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 110, -1));

        jtcost.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtcost.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(jtcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 80, -1));

        jbutInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gestion-de-la-informacion.png"))); // NOI18N
        jbutInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutInfoActionPerformed(evt);
            }
        });
        jPanel1.add(jbutInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 40, 30));

        jLabel3.setBackground(new java.awt.Color(255, 35, 1));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" Agregar Productos");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo4.jpg"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 String parametro4 = "";
    int parametro3 = 0;
    String index2(String par, int par2){
    parametro4 = par;
    parametro3 = par2;
    
        return par;
    }
    private void jButRegresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegresaActionPerformed
        opciones obj = new opciones();
        obj.index(parametro4,parametro3);
        obj.setVisible(true);
        dispose();
       
        
    }//GEN-LAST:event_jButRegresaActionPerformed
    static Scanner leer = new Scanner(System.in);
    String url = "jdbc:mysql://localhost:3306/sistemaventas?useTimezone=true&serverTimezone=UTC&useSSL=false";
    String username = "root";
    String password = "12345";
    
    
    private void jButAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAddActionPerformed
        int Stock, Stockm, id;
        String SQL, desc, tipo;
        float preciov, cost;
        try {
            Connection conexion = DriverManager.getConnection(url, username, password);
            Statement statement = conexion.createStatement();
            ResultSet rs = statement.executeQuery("SELECT*FROM productos");
            
           boolean isNumeric =  jtID.getText().matches("\\d*");           
           boolean isNumeric2 = jtstock.getText().matches("\\d*");           
           boolean isNumeric3 = jtstockm.getText().matches("\\d*");           
           boolean isNumeric4 = jtprev.getText().matches("\\d*(\\.\\d+)?*");           
           boolean isNumeric5 = jtcost.getText().matches("\\d*(\\.\\d+)?*");

            if(jtID.getText()!="" && isNumeric && isNumeric2 && isNumeric3 && isNumeric4 && isNumeric5){
                
            id = Integer.parseInt(jtID.getText());
            Stock = Integer.parseInt(jtstock.getText());
            Stockm = Integer.parseInt(jtstockm.getText());
            desc = jtdesc.getText();
            tipo = jtipo.getText();
            preciov = Float.parseFloat(jtprev.getText());
            cost = Float.parseFloat(jtcost.getText());
  
            SQL = "INSERT INTO productos (idproductos,PrecioVenta,Descripcion,Stock,StockMinimo,TipoProducto,Costo)"
                    + "Values("
                    + "\"" + id + "\","
                    + "\"" + preciov + "\","
                    + "\"" + desc + "\","
                    + "\"" + Stock + "\","
                    + "\"" + Stockm + "\","
                    + "\"" + tipo + "\","
                    + "\"" + cost + "\")";

            statement.execute(SQL);
            
            JOptionPane.showMessageDialog(null, "Se Agrego producto correctamente");
            jtID.setText("");
            jtstock.setText("");
            jtstockm.setText("");
            jtdesc.setText("");
            jtipo.setText("");
            jtprev.setText("");
            jtcost.setText("");
            }//if 
        } catch (SQLException ex) {
            System.out.println("Error de conexion: " + ex);
        }
    }//GEN-LAST:event_jButAddActionPerformed

    private void jbutInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutInfoActionPerformed
        JOptionPane.showMessageDialog(null, "En esta ventana se va a modificar los productos, para esto: \n"
                + "1.- Llena los campos correspondientes. \n "
                + "2.- Una vez llenos presiona el boton agregar. ");
    }//GEN-LAST:event_jbutInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlAlmacen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel icono;
    private javax.swing.JButton jButAdd;
    private javax.swing.JButton jButRegresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbutInfo;
    private javax.swing.JTextField jtID;
    private javax.swing.JTextField jtcost;
    private javax.swing.JTextField jtdesc;
    private javax.swing.JTextField jtipo;
    private javax.swing.JTextField jtprev;
    private javax.swing.JTextField jtstock;
    private javax.swing.JTextField jtstockm;
    // End of variables declaration//GEN-END:variables
}
