
import java.util.Scanner;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author luisf
 */
public class Eliminar extends javax.swing.JFrame {
DefaultTableModel modelo;
    /**
     * Creates new form Eliminar
     */
    public Eliminar() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        };

        modelo.addColumn("ID producto");
        modelo.addColumn("Precio ");
        modelo.addColumn("Descripción");
        modelo.addColumn("Stock");
        modelo.addColumn("Stock Minimo");
        modelo.addColumn("Tipo");
        modelo.addColumn("Costo");
        this.jTable1.setModel(modelo);
        jTable1.getTableHeader().setReorderingAllowed(false);
        
        jTable1.getTableHeader().setResizingAllowed(false);
        jbutcancel.setEnabled(false);
        
        Buscar();
    }
    String[] vector = new String[7];
    String[] vectorR = new String[7];

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtBusca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButEliminar = new javax.swing.JButton();
        jButRegresa = new javax.swing.JButton();
        jbutcancel = new javax.swing.JButton();
        icono = new javax.swing.JLabel();
        jButBuscar = new javax.swing.JButton();
        jbutInfo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eliminar producto");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBuscaActionPerformed(evt);
            }
        });
        jPanel1.add(jtBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 190, 30));

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre del producto: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 700, 240));

        jButEliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trash-can_115312.png"))); // NOI18N
        jButEliminar.setText("Eliminar");
        jButEliminar.setBorder(null);
        jButEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 100, 30));

        jButRegresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion.png"))); // NOI18N
        jButRegresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegresaActionPerformed(evt);
            }
        });
        jPanel1.add(jButRegresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 50, 30));

        jbutcancel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbutcancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton-eliminar.png"))); // NOI18N
        jbutcancel.setText("Cancelar");
        jbutcancel.setBorder(null);
        jbutcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutcancelActionPerformed(evt);
            }
        });
        jPanel1.add(jbutcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 110, 30));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/shop-icon_34368.png"))); // NOI18N
        jPanel1.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        jButBuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vidrio-de-aumento.png"))); // NOI18N
        jButBuscar.setText("Buscar");
        jButBuscar.setBorder(null);
        jButBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jButBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 100, 30));

        jbutInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gestion-de-la-informacion.png"))); // NOI18N
        jbutInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutInfoActionPerformed(evt);
            }
        });
        jPanel1.add(jbutInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 40, 30));

        jLabel3.setBackground(new java.awt.Color(255, 35, 1));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Eliminar producto");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo4.jpg"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBuscaActionPerformed
     String parametro4 = "";
    int parametro3 = 0;
    String index2(String par, int par2){
    parametro4 = par;
    parametro3 = par2;
    
        return par;
    }

    static Scanner leer = new Scanner(System.in);
    String url = "jdbc:mysql://localhost:3306/sistemaventas?useTimezone=true&serverTimezone=UTC&useSSL=false";
    String username = "root";
    String password = "12345";

    private void jButRegresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegresaActionPerformed
        opciones obj = new opciones();
        obj.index(parametro4,parametro3);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButRegresaActionPerformed

    private void jButEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEliminarActionPerformed
        String SQL;

        try {
            Connection conexion = DriverManager.getConnection(url, username, password);
            Statement statement = conexion.createStatement();

            if (jTable1.getSelectedRow() != -1) {
                String id = (String) modelo.getValueAt(jTable1.getSelectedRow(), 0);
                int id1 = Integer.parseInt(id);
                ResultSet rs = statement.executeQuery("SELECT*FROM productos WHERE idproductos = " + id1);
                while (rs.next()) {
                    vectorR[0] = String.valueOf(rs.getInt("idproductos"));
                    vectorR[1] = Float.toString(rs.getFloat("PrecioVenta"));
                    vectorR[2] = rs.getString("Descripcion");
                    vectorR[3] = String.valueOf(rs.getInt("Stock"));
                    vectorR[4] = String.valueOf(rs.getInt("StockMinimo"));
                    vectorR[5] = rs.getString("TipoProducto");
                    vectorR[6] = String.valueOf(rs.getInt("Costo"));
                }//while
                 SQL = "DELETE FROM ventaprodcuto WHERE IdProducto =" + id1;
                statement.execute(SQL);
                SQL = "DELETE FROM productos WHERE idproductos = " + id1 + "";

                statement.execute(SQL);
                Buscar();
                JOptionPane.showMessageDialog(null, "Se eliminó correctamente.");
                
                jbutcancel.setEnabled(true);

            } else {
                JOptionPane.showMessageDialog(null, "Selecciona una fila.");
            }

        } catch (SQLException ex) {
            System.out.println("Error de conexion: " + ex);
        }

    }//GEN-LAST:event_jButEliminarActionPerformed

    private void jButBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBuscarActionPerformed
        Buscar();
    }//GEN-LAST:event_jButBuscarActionPerformed

    private void jbutcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutcancelActionPerformed
        String SQL;

        try {
            Connection conexion = DriverManager.getConnection(url, username, password);
            Statement statement = conexion.createStatement();

            int id2 = Integer.parseInt(vectorR[0]);
            float prev2 = Float.parseFloat(vectorR[1]);
            String desc2 = (vectorR[2]);
            int stock2 = Integer.parseInt(vectorR[3]);
            int stockm2 = Integer.parseInt(vectorR[4]);
            String tipo2 = (vectorR[5]);
            float cost2 = Float.parseFloat(vectorR[6]);

            SQL = "INSERT INTO productos (idproductos,PrecioVenta,Descripcion,Stock,StockMinimo,TipoProducto,"
                    + "Costo)"
                    + "Values("
                    + "\"" + id2 + "\","
                    + "\"" + prev2 + "\","
                    + "\"" + desc2 + "\","
                    + "\"" + stock2 + "\","
                    + "\"" + stockm2 + "\","
                    + "\"" + tipo2 + "\","
                    + "\"" + cost2 + "\")";

            statement.execute(SQL);
            Buscar();
            JOptionPane.showMessageDialog(null, "Se ha cancelado la operación.");

            jbutcancel.setEnabled(false);

        } catch (SQLException ex) {
            System.out.println("Error de conexion: " + ex);
        }
    }//GEN-LAST:event_jbutcancelActionPerformed

    private void jbutInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutInfoActionPerformed
          JOptionPane.showMessageDialog(null, "En esta ventana se va a eliminar los productos para esto: \n"
                  + "1.- Selecciona una fila del producto que quieras eliminar. \n "
                  + "2.- Después selecciona el botón eliminar y dale click. \n"
                  + "\n"
                  + "En caso de querer cancelar la eliminación da click en el botón.");
    }//GEN-LAST:event_jbutInfoActionPerformed

    public void Buscar() {
        String busca = jtBusca.getText();
        modelo.getDataVector().removeAllElements();//Limpia la tabla
        jTable1.updateUI();

        try {
            Connection conexion = DriverManager.getConnection(url, username, password);
            Statement statement = conexion.createStatement();
            ResultSet rs = statement.executeQuery("SELECT*FROM productos WHERE descripcion LIKE '%" + busca + "%'");
            while (rs.next()) {
                vector[0] = String.valueOf(rs.getInt("idproductos"));
                vector[1] = Float.toString(rs.getFloat("PrecioVenta"));
                vector[2] = rs.getString("Descripcion");
                vector[3] = String.valueOf(rs.getInt("Stock"));
                vector[4] = String.valueOf(rs.getInt("StockMinimo"));
                vector[5] = rs.getString("TipoProducto");
                vector[6] = String.valueOf(rs.getInt("Costo"));
                modelo.addRow(vector);

            }//while
        } catch (SQLException ex) {
            System.out.println("Error de conexion: " + ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel icono;
    private javax.swing.JButton jButBuscar;
    private javax.swing.JButton jButEliminar;
    private javax.swing.JButton jButRegresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbutInfo;
    private javax.swing.JButton jbutcancel;
    private javax.swing.JTextField jtBusca;
    // End of variables declaration//GEN-END:variables
}
