
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author luisf
 */
public class ReporteVentas extends javax.swing.JFrame {
DefaultTableModel modelo;



    /**
     * Creates new form ReporteVentas
     */
    public ReporteVentas() {
        initComponents();
         this.setLocationRelativeTo(null);
         modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
                //bloqueamos las toda la tabla 
            }
        };
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio c/u");
        modelo.addColumn("Total");
        this.jTable1.setModel(modelo);
        jTable1.getTableHeader().setReorderingAllowed(false);
        
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.getTableHeader().setResizingAllowed(false);
        
        txtTotal.setEditable(false);
    }
String url = "jdbc:mysql://localhost:3306/sistemaventas?useTimezone=true&serverTimezone=UTC&useSSL=false";
    String username = "root";
    String password = "12345";
    String[] vector = new String[4];
     int cant=0;
     float total=0;
     float totalM=0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButRegresa = new javax.swing.JButton();
        jdate2 = new com.toedter.calendar.JDateChooser();
        jdate1 = new com.toedter.calendar.JDateChooser();
        butgenerar = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jLabel4Toto = new javax.swing.JLabel();
        jLabel4Toto1 = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        jLabel4Toto2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 560, 280));

        jButRegresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion.png"))); // NOI18N
        jButRegresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegresaActionPerformed(evt);
            }
        });
        jPanel1.add(jButRegresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 50, 30));

        jdate2.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(jdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 130, 30));

        jdate1.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(jdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 130, 30));

        butgenerar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        butgenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grafico-de-barras (1).png"))); // NOI18N
        butgenerar.setText("Generar");
        butgenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butgenerarActionPerformed(evt);
            }
        });
        jPanel1.add(butgenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, 30));

        txtTotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(0, 102, 102));
        txtTotal.setMaximumSize(new java.awt.Dimension(6, 20));
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 110, 30));

        jLabel4Toto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4Toto.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4Toto.setText("Fecha Inicial:");
        jPanel1.add(jLabel4Toto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, 30));

        jLabel4Toto1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4Toto1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4Toto1.setText("Fecha Final");
        jPanel1.add(jLabel4Toto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 110, 30));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/shop-icon_34368.png"))); // NOI18N
        jPanel1.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        jLabel4Toto2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4Toto2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4Toto2.setText("Total $:");
        jPanel1.add(jLabel4Toto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 50, 30));

        jLabel3.setBackground(new java.awt.Color(255, 35, 1));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Reporte de Ventas");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo4.jpg"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 580, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public int totalP(int idP, Date date, Date date2){
         long d = date.getTime();
        java.sql.Date fecha1 = new java.sql.Date(d);
        long d2= date2.getTime();
        java.sql.Date fecha2 = new java.sql.Date(d2);
      try {
          Connection conexion = DriverManager.getConnection(url, username, password);
          Statement statement = conexion.createStatement();
          ResultSet rs2 = statement.executeQuery("Select ventaprodcuto.IdProducto, ventaprodcuto.Cantidad, ventaprodcuto.Monto"
          + " from ventaprodcuto\n" +"LEFT JOIN venta ON ventaprodcuto.idVenta = venta.idVenta Where venta.Fecha between '"
          +fecha1+" 00:00:00' and '"+fecha2+" 23:59:59';");
          
          while(rs2.next()){
              int idV = rs2.getInt("IdProducto");
              if(idP == idV){ //Inicio if
                               cant= cant + rs2.getInt("Cantidad"); 
                               total= total + rs2.getFloat("Monto");    
                               
                            }// Fin if
          }
      } catch (SQLException ex) {
                    System.out.println("Error de conexion: " + ex);
                }
      return 0;
  }
    private void jButRegresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegresaActionPerformed
        opciones obj = new opciones();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButRegresaActionPerformed

    private void butgenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butgenerarActionPerformed
       try{
         modelo.getDataVector().removeAllElements();//Limpia la tabla
         jTable1.updateUI();
        Date date = jdate1.getDate();
        
        Date date2 = jdate2.getDate();
        
        if(date.getTime()<=date2.getTime()){
             try {
                    Connection conexion = DriverManager.getConnection(url, username, password);
                    Statement statement = conexion.createStatement();
                    ResultSet rs = statement.executeQuery("SELECT*FROM productos");
                   
                    int idP2=0;
                    float precioV2=0;
                    String desc2="";
                    
                    while(rs.next()){ //Inicio primer while
                        idP2 = rs.getInt("idproductos");
                        precioV2=rs.getFloat("PrecioVenta");
                        desc2=rs.getString("Descripcion");
                        totalP(idP2,date,date2);
                        vector[0]=desc2;
                        vector[1]=String.valueOf(cant);
                        vector[2]=Float.toString(precioV2);
                        vector[3]=Float.toString(total);
                        modelo.addRow(vector);
                        totalM = totalM +total;
                        cant=0;
                        total=0;
                    }// Fin primer while
                } catch (SQLException ex) {
                    System.out.println("Error de conexion: " + ex);
                }
        }else{
            JOptionPane.showMessageDialog(this, "Elija una fecha mayor a la inicial");
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Favor de marcar ambas fechas");
        }
       txtTotal.setText(""+totalM);
       totalM = 0;
    }//GEN-LAST:event_butgenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton butgenerar;
    private javax.swing.JLabel icono;
    private javax.swing.JButton jButRegresa;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4Toto;
    private javax.swing.JLabel jLabel4Toto1;
    private javax.swing.JLabel jLabel4Toto2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser jdate1;
    private com.toedter.calendar.JDateChooser jdate2;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
